# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import icons_rc

class Ui_menu(object):
    def setupUi(self, menu):
        menu.setObjectName("menu")
        menu.resize(438, 328)
        menu.setStyleSheet("background-color:rgba(16, 30, 41, 240);")
        self.centralwidget = QtWidgets.QWidget(menu)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 431, 321))
        self.label.setStyleSheet("")
        self.label.setText("")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 20, 391, 281))
        self.label_2.setStyleSheet("background-color:rgba(0,0,0,200);\n"
"border-radius:20px;")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(40, 40, 160, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("background-color: rgba(200, 200,200,150);\n"
"font: 25 9pt \"Bookman Old Style\";\n"
"color: rgb(255,255,255)")
        self.lineEdit_2.setFrame(False)
        self.lineEdit_2.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.verticalLayout.addWidget(self.lineEdit_2)
        self.RC_RecbeamCal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RC_RecbeamCal.setStyleSheet("QPushButton#RC_RecbeamCal{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"\n"
"}\n"
"\n"
"QPushButton#RC_RecbeamCal:hover{\n"
"background-color:rgba(2, 65, 118, 200);\n"
"}\n"
"\n"
"QPushButton#RC_RecbeamCal:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}")
        self.RC_RecbeamCal.setObjectName("RC_RecbeamCal")
        self.verticalLayout.addWidget(self.RC_RecbeamCal)
        self.RC_TbeamCal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RC_TbeamCal.setStyleSheet("QPushButton#RC_TbeamCal{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"\n"
"}\n"
"\n"
"QPushButton#RC_TbeamCal:hover{\n"
"background-color:rgba(2, 65, 118, 200);\n"
"}\n"
"\n"
"QPushButton#RC_TbeamCal:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/t.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.RC_TbeamCal.setIcon(icon)
        self.RC_TbeamCal.setObjectName("RC_TbeamCal")
        self.verticalLayout.addWidget(self.RC_TbeamCal)
        self.RC_ColumnCal = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.RC_ColumnCal.setStyleSheet("QPushButton#RC_ColumnCal{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"\n"
"}\n"
"\n"
"QPushButton#RC_ColumnCal:hover{\n"
"background-color:rgba(2, 65, 118, 200);\n"
"}\n"
"\n"
"QPushButton#RC_ColumnCal:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}")
        self.RC_ColumnCal.setObjectName("RC_ColumnCal")
        self.verticalLayout.addWidget(self.RC_ColumnCal)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(220, 40, 160, 91))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Bookman Old Style")
        font.setPointSize(9)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(3)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("background-color: rgba(200, 200,200,150);\n"
"font: 25 9pt \"Bookman Old Style\";\n"
"color: rgb(255,255,255)")
        self.lineEdit_4.setFrame(False)
        self.lineEdit_4.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.verticalLayout_4.addWidget(self.lineEdit_4)
        self.RC_BeamDsgn = QtWidgets.QPushButton(self.verticalLayoutWidget_4)
        self.RC_BeamDsgn.setStyleSheet("QPushButton#RC_BeamDsgn{\n"
"background-color:rgba(2, 65, 118, 255);\n"
"color:rgba(255, 255, 255, 200);\n"
"\n"
"}\n"
"\n"
"QPushButton#RC_BeamDsgn:hover{\n"
"background-color:rgba(2, 65, 118, 200);\n"
"}\n"
"\n"
"QPushButton#RC_BeamDsgn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(2, 65, 118, 100);\n"
"background-position:calc(100% - 10px)center;\n"
"}")
        self.RC_BeamDsgn.setObjectName("RC_BeamDsgn")
        self.verticalLayout_4.addWidget(self.RC_BeamDsgn)
        menu.setCentralWidget(self.centralwidget)

        self.retranslateUi(menu)
        QtCore.QMetaObject.connectSlotsByName(menu)

    def retranslateUi(self, menu):
        _translate = QtCore.QCoreApplication.translate
        menu.setWindowTitle(_translate("menu", "MainWindow"))
        self.lineEdit_2.setText(_translate("menu", "           Calculation"))
        self.RC_RecbeamCal.setText(_translate("menu", " 矩形梁強度計算"))
        self.RC_TbeamCal.setText(_translate("menu", " T形梁強度計算"))
        self.RC_ColumnCal.setText(_translate("menu", "柱強度計算"))
        self.lineEdit_4.setText(_translate("menu", "              Design"))
        self.RC_BeamDsgn.setText(_translate("menu", " 梁配筋設計"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    menu = QtWidgets.QMainWindow()
    ui = Ui_menu()
    ui.setupUi(menu)
    menu.show()
    sys.exit(app.exec_())
